server:
  port: 8080
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serializer.StringSerializer
      value-serializer: org.apache.kafka.common.serializer.StringSerializer